### ISSUE TITLE
Convert canvas in png

### ISSUE THREAD

**Issue by joaquinND10** [Ovilia/Polyvia#2]
Hello, I tried to turn the canvas in PNG, but for some reason only one image is saved in black, like layers, any clues?

**Comment by Ovilia** [comment]
@joaquinND10 This is because the canvas is set to be the size of the window. So if the image is wider, there would be black area in top and bottom.

**Comment by joaquinND10** [comment]
I mean to convert the image into png, everything looks black, you can see the code that is what gives the canvas, how I can fix this? ...

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB4AAAAOyCAYAAACSX8hzAAAgAElEQVR4nOzOsQnAQBAEseu/6XcTCwNGgXLd3T0AAAAAAAAAfiEPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAAAAAAAAYCMPAAAAAAAAALCRBwAAAAAAAADYyAMAAAAAAAAAbOQBAAAAAAAAADbyAAAAAAAAAAAbeQAAAAAAAACAjTwAAAAAAAAAwEYeAAAAAAAAAGAjDwAAAAAAAACwkQcAAAAAAAAA2MgDAAAAAAAAAGzkAQAAAAAAAAA28gAAAAAAAAAAG3kAAAAAAAAAgI08AAAAAAAAAMBGHgAAAAAAAABgIw8AAAAAAAAAsJEHAAAAAAAAANjIAwAAAAAAAABs5AEAAAAAAAAANvIAAAAAAAAAABt5AAAAAAAAAICNPAAAAAAAAADARh4AAICv3Tm0AQAAYBj0/9d7oskMAg8AAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAFgiHosAAASrSURBVAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAABo3AMAAAAAAAAANO4BAAAAAAAAABr3AAAAAAAAAACNewAAAAAAAACAxj0AAAAAAAAAQOMeAAAAAAAAAKBxDwAAAAAAAADQuAcAAAAAAAAAaNwDAAAAAAAAADTuAQAAAAAAAAAa9wAAAAAAAAAAjXsAAAAAAAAAgMY9AAAAAAAAAEDjHgAAAAAAAACgcQ8AAAAAAAAA0LgHAAAAAAAAAGjcAwAAAAAAAAA07gEAAAAAAAAAGvcAAAAAAAAAAI17AAAAAAAAAIDGPQAAAAAAAABA4x4AAAAAAAAAoHEPAAAAAAAAANC4BwAAAAAAAAAIDA675yUwBexWAAAAAElFTkSuQmCC

**Comment by Ovilia** [comment]
How do you get this?
By right-clicking and saving the low-poly canvas, you should get exactly as you see in the canvas.

**Comment by reiwacoder** [comment]
Try the demo with Mac Firefox, what it saved is black, then I open Chrome to save generated low poly png, it's allright.
